export const usersExamples = [
	{
		id: "1",
		name: "Alice",
		email: "alice@example.com",
		role: "admin",
		status: "active",
	},
	{
		id: "2",
		name: "Bob",
		email: "bob@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "3",
		name: "Charlie",
		email: "charlie@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "4",
		name: "David",
		email: "david@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "5",
		name: "Emily",
		email: "emily@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "6",
		name: "Finn",
		email: "finn@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "7",
		name: "Grace",
		email: "grace@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "8",
		name: "Henry",
		email: "henry@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "9",
		name: "Isabella",
		email: "isabella@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "10",
		name: "Jack",
		email: "jack@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "11",
		name: "Olivia",
		email: "olivia@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "12",
		name: "Sophia",
		email: "sophia@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "13",
		name: "William",
		email: "william@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "14",
		name: "Mia",
		email: "mia@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "15",
		name: "Ethan",
		email: "ethan@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "16",
		name: "Ava",
		email: "ava@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "17",
		name: "Noah",
		email: "noah@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "18",
		name: "Emma",
		email: "emma@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "19",
		name: "Liam",
		email: "liam@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "20",
		name: "Charlotte",
		email: "charlotte@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "21",
		name: "Olivia",
		email: "olivia23@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "22",
		name: "Noah",
		email: "noahsmith@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "23",
		name: "Ethan",
		email: "ethanlee@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "24",
		name: "Ava",
		email: "avajones@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "25",
		name: "Liam",
		email: "liamwilson@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "26",
		name: "Emma",
		emai: "emmabrown@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "27",
		name: "Charlotte",
		email: "charlottetaylor@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "28",
		name: "Benjamin",
		email: "benjaminmartin@example.com",
		role: "user",
		status: "active",
	},
	{
		id: "29",
		name: "Mia",
		email: "miaanderson@example.com",
		role: "user",
		status: "active",
	},
];
