export type status =
	| "INVALID_CREDENTIALS"
	| "USER_EXISTS"
	| "ERROR"
	| "SUCCESS"
	| "USER_NOT_EXISTS"
	| "INVALID_PASSWORD"
	| "ERRORLOGIN"
	| "SERVERERROR"
	| "ERROR"
	| "INVALID_FORM"
	| "INVALID_QUESTIONS";
